### ISSUE TITLE
Signing protocol

### ISSUE THREAD

**Issue by rnicoll** [dogecoinfoundation/corefunds#10]
I need a decision from the collected group. Once we have a multisignature address ready to go, we need an agreed protocol for signing. Specifically, we’ll need tools to generate the unsigned transaction, the individual signatures, and compose them into a final transaction to relay.

There are two toolchains that I am aware of, which can be used to signing a spending transaction from a multisignature address on Dogecoin:

* Patrick’s https://github.com/patricklodder/devfundtx tool, which was used for initial payouts.
* Dogecoin Core 1.21, which has been successfully used for recent 1.14.x payouts.

Generally I favour the former, but it requires more work from Patrick, so I wanted to list the pros and cons and get feedback.

The Dogecoin Core 1.21 tool chain has three main drawbacks:

* The tool to build the transaction in the first place is not yet open source - due to when it was written it’s under copyright by my employer, and while I’ve started the process to open source it, that’s likely to take 2-3 weeks due to approvals.
* The generally used version of Dogecoin Core 1.21 for signing is based on an experimental branch. In theory the latest development branch should work, as the node is just being used as a signing tool and so does not require most of the Dogecoin adjustments to be in place.
* By design Dogecoin Core won’t include more signatures than necessary, in order to avoid blockchain spam. Meaning for a 3/5 address it will at most include 3 signatures in the transaction.

These are manageable; the generated transaction can (and should) be verified by each individual signer before signing, and therefore the lack of the source to the transaction build tool should not be a substantial issue. The development branch of 1.21 should work for signing, as it does not need to sync, although we'd need to confirm this or use the experimental version. The signatures issue can be handled by the keyholders recording their signatures outside of the blockchain for the record.

On the other hand Patrick’s tools are stand-alone and therefore easier for individuals to confirm the validity of, however this would push maintenance work onto Patrick, so I’m cautious to ask that.

What do others think?

**Comment by chromatic** [comment]
I think the sources of the tools and toolchains we use to build any transactions must be open source and public. I'm comfortable if the policy states that but doesn't mandate any specific tool or toolchain.

**Comment by rnicoll** [comment]
The 1.21 approach is PSBT; shall we go with that? The tool to generate the transaction (which is really just collating UTXO, shuffling and estimating fees) should be open source once sign-offs are done. If 1.21's dev branch works for signing (should do), we should be able to progress with that.

**Comment by rnicoll** [comment]
To clarify; the actual assembling the PSBT happens in the node, the tool just finds enough UTXO and avoids manual handling. Actually occurs there's no reason the input JSON can't be pulled out and provided so others can verify it.

**Comment by rnicoll** [comment]
The core of the question is whether we're okay to use PSBT as the exchange format, yes, and then custodians can choose their tool of choice as long as it meets that.
