### ISSUE TITLE
Old agreement in your announcement!

### ISSUE THREAD

**Issue by kstabel** [dogecoinfoundation/corefunds#21]
Hello,

https://foundation.dogecoin.com/announcements/2022-12-31-corefund/

This is not the document that was agreed on.  Please fix and publicly announce that a mistake was made.

**Comment by rnicoll** [comment]
Raised (and has been merged) a PR with the corrected text. I'll leave the Foundation to work out if they want to flag it as a revision in text, do a tweet, something else.
