### ISSUE TITLE
purpose/policy docs

### ISSUE THREAD

**Issue by patricklodder** [dogecoinfoundation/corefunds#7]
Hi! I have my keys ready for over a day now, but I am waiting on the purpose & policy text to be put here. Unfortunately, I cannot provide keys when there is no strict publicly documented policy text - people usually don't provide signatures before the contract is made up where I am from, but perhaps I truly am alien and preemptive signing is an actual thing. Nevertheless, I'd rather be alien in that case. Apologies.

**Comment by rnicoll** [comment]
Apologies, I had notification settings for this repo set too low and didn't see this until it was pointed out. I received the latest text yesterday and raised a PR with it the same day.

Reminded though; you should have had an invite as an external collaborator on the repo so you can formally approve PRs and they can be merged. Did that not arrive? If not I'll resend the invite, obviously others can approve so the PR can be merged but it would be good to have everyone able to approve PRs.

**Comment by rnicoll** [comment]
In which case any concerns with me reconfiguring the repo to allow submission of PRs without strict approval? It means once you verbally confirm something I can merge, where currently the configuration is set so I can't, and... obviously yes I can change that, but that's not the point.

**Comment by rnicoll** [comment]
I've updated permissions so PRs can be merged without a GitHub approval, hope that's okay.
