### ISSUE TITLE
Accidental merge, confirming no issues

### ISSUE THREAD

**Issue by marshallhayner** [dogecoinfoundation/corefunds#9]
Sorry guys, I accidentally merged this before everyone could ACK, are we all in agreement on the policy?

**Comment by rnicoll** [comment]
ACK from me

**Comment by chromatic** [comment]
ACK from me for 7ddda81 as well.

**Comment by michilumin** [comment]
ack on https://github.com/dogecoinfoundation/corefunds/commit/7ddda81dae20023f9c941b7bf9c4a1a5c9175bf2

**Comment by rnicoll** [comment]
> ```
> 3280422142b27a16d254a6b4be6482670ed282a0aa4759897d0a19971af9fabe  
> ```

I get that hash with LF rather than CRLF line endings. Raised https://github.com/dogecoinfoundation/corefunds/pull/11 to avoid line endings in POLICY.md being OS specific.
